version: 0.1

phases:
  pre_build:
    commands:
      - echo Loggin in to Amazon ECR ...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - echo Logging into DockerHub ...
      - docker login --username="$DOCKER_HUB_USERNAME" --password="$DOCKER_HUB_PASSWORD"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image ...
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG 
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
